"""conversations and turns

Revision ID: 7b4b96a30bcf
Revises:
Created: 2026-08-02 19:26:49.054772
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7b4b96a30bcf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column("last_turn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversation_recent", ["archived", "last_turn_at"], unique=False
        )

    op.create_table(
        "turns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("final_answer", sa.Text(), nullable=False),
        sa.Column("topic", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verdict_kind", sa.String(length=20), nullable=False),
        sa.Column("solution", sa.JSON(), nullable=False),
        sa.Column("verdict", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("bookmarked", sa.Boolean(), nullable=False),
        sa.Column("bookmarked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_turns_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
    )
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.create_index(
            "ix_turn_bookmarked_at", ["bookmarked", "bookmarked_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_turns_bookmarked"), ["bookmarked"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_turns_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_turns_topic"), ["topic"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_verified"), ["verified"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turns_verified"))
        batch_op.drop_index(batch_op.f("ix_turns_topic"))
        batch_op.drop_index(batch_op.f("ix_turns_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_turns_bookmarked"))
        batch_op.drop_index("ix_turn_bookmarked_at")

    op.drop_table("turns")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index("ix_conversation_recent")

    op.drop_table("conversations")
    # ### end Alembic commands ###
