"""practice question bank

Revision ID: 2c70eaa99927
Revises: 7b4b96a30bcf
Created: 2026-08-02 20:10:00.556337
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2c70eaa99927"
down_revision: str | None = "7b4b96a30bcf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verdict_kind", sa.String(length=20), nullable=False),
        sa.Column("question", sa.JSON(), nullable=False),
        sa.Column("verdict", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("correct", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bookmarked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_questions")),
    )
    with op.batch_alter_table("practice_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_practice_questions_bookmarked"), ["bookmarked"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_practice_questions_difficulty"), ["difficulty"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_practice_questions_topic"), ["topic"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_practice_questions_verified"), ["verified"], unique=False
        )
        batch_op.create_index(
            "ix_question_selection", ["topic", "difficulty", "verified"], unique=False
        )
        batch_op.create_index("ix_question_unattempted", ["topic", "attempts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("practice_questions", schema=None) as batch_op:
        batch_op.drop_index("ix_question_unattempted")
        batch_op.drop_index("ix_question_selection")
        batch_op.drop_index(batch_op.f("ix_practice_questions_verified"))
        batch_op.drop_index(batch_op.f("ix_practice_questions_topic"))
        batch_op.drop_index(batch_op.f("ix_practice_questions_difficulty"))
        batch_op.drop_index(batch_op.f("ix_practice_questions_bookmarked"))

    op.drop_table("practice_questions")
    # ### end Alembic commands ###
