"""review records

Revision ID: 20d3cb1cb1ce
Revises: 2c70eaa99927
Created: 2026-08-03 04:27:59.163397
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20d3cb1cb1ce"
down_revision: str | None = "2c70eaa99927"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("working", sa.Text(), nullable=False),
        sa.Column("verdict", sa.String(length=30), nullable=False),
        sa.Column("topic", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("mistake_count", sa.Integer(), nullable=False),
        sa.Column("error_types", sa.String(length=200), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("overridden_from", sa.String(length=30), nullable=False),
        sa.Column("review", sa.JSON(), nullable=False),
        sa.Column("verdicts", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_records")),
    )
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_records_topic"), ["topic"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_review_records_verdict"), ["verdict"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_records_verified"), ["verified"], unique=False
        )
        batch_op.create_index("ix_review_topic_created", ["topic", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_records", schema=None) as batch_op:
        batch_op.drop_index("ix_review_topic_created")
        batch_op.drop_index(batch_op.f("ix_review_records_verified"))
        batch_op.drop_index(batch_op.f("ix_review_records_verdict"))
        batch_op.drop_index(batch_op.f("ix_review_records_topic"))

    op.drop_table("review_records")
    # ### end Alembic commands ###
