"""quizzes and answers

Revision ID: 41f0a78f6799
Revises: 20d3cb1cb1ce
Created: 2026-08-03 04:53:32.419733
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "41f0a78f6799"
down_revision: str | None = "20d3cb1cb1ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quizzes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("topic", sa.String(length=40), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("question_ids", sa.JSON(), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("marks_correct", sa.Integer(), nullable=False),
        sa.Column("marks_wrong", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("wrong_count", sa.Integer(), nullable=False),
        sa.Column("unattempted_count", sa.Integer(), nullable=False),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
    )
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.create_index("ix_quiz_recent", ["status", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_quizzes_status"), ["status"], unique=False)

    op.create_table(
        "quiz_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("selected", sa.JSON(), nullable=False),
        sa.Column("written", sa.Text(), nullable=False),
        sa.Column("self_marked", sa.Boolean(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("marks", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_answers_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_answers")),
    )
    with op.batch_alter_table("quiz_answers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quiz_answers_quiz_id"), ["quiz_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_answers_quiz_id"))

    op.drop_table("quiz_answers")
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quizzes_status"))
        batch_op.drop_index("ix_quiz_recent")

    op.drop_table("quizzes")
    # ### end Alembic commands ###
